language: go

branches:
  only:
  - master

go:
  - 1.9.x

install: 
  - go get github.com/StackExchange/dnscontrol
  - mv creds.json.env creds.json
  - '[[ $TRAVIS_EVENT_TYPE = "push" ]] && op="push" || op="preview"'

script: 
  - echo $op
  - dnscontrol preview -providers cloudflare

