language: go

branches:
  only:
  - master

go:
  - 1.9.x

install: 
  - go get github.com/StackExchange/dnscontrol
  - mv creds.json.env creds.json
  - '[[ $TRAVIS_EVENT_TYPE = "push" && $TRAVIS_BRANCH = "master" ]] && op="push" || op="preview"'

script: 
  - dnscontrol $op -providers cloudflare

